version: "3.9"

services:
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    depends_on:
      - mysqldb
    build: .
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - MYSQLDB_HOST=${MYSQLDB_HOST}
      - MYSQLDB_USER=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQLDB_DATABASE=${MYSQLDB_DATABASE}
      - MYSQLDB_PORT=${MYSQLDB_DOCKER_PORT}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_PLAN_STD=${MP_PLAN_STD}
      - MP_PLAN_PREM=${MP_PLAN_PREM}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    restart: unless-stopped
    command: node src/app.js
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:3000/', r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 15s
      timeout: 3s
      retries: 10

volumes:
  db_data:
