'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    try {
      await queryInterface.bulkInsert('order', [
        // Usuario 1
        {
          id: 1,
          user_id: 1,
          commerce_id: 1,
          address_id: 1,
          created_at: new Date('2024-09-25'),
          total_amount: 300,               // = 200 + 100
          status: 'PENDING',
          delivery_type: 'pickup',
          payment_method: 'cash',
          items_quantity: 3                // = 2 + 1
        },
        {
          id: 2,
          user_id: 1,
          commerce_id: 2,
          address_id: 1,
          created_at: new Date('2024-09-26'),
          total_amount: 300,               // = 1*100 + 1*200
          status: 'PENDING',
          delivery_type: 'pickup',
          payment_method: 'cash',
          items_quantity: 2                // = 1 + 1
        },
        {
          id: 3,
          user_id: 1,
          commerce_id: 3,
          address_id: 1,
          created_at: new Date('2024-09-27'),
          total_amount: 700,               // = 2*200 + 1*300
          status: 'DELIVERED',
          delivery_type: 'delivery',
          payment_method: 'cash',
          items_quantity: 3                // = 2 + 1
        },
        {
          id: 4,
          user_id: 1,
          commerce_id: 4,
          address_id: 1,
          created_at: new Date('2024-09-28'),
          total_amount: 800,               // = 2*200 + 2*200
          status: 'COMPLETED',
          delivery_type: 'pickup',
          payment_method: 'cash',
          items_quantity: 4                // = 2 + 2
        },
        {
          id: 5,
          user_id: 1,
          commerce_id: 5,
          address_id: 1,
          created_at: new Date('2024-09-29'),
          total_amount: 900,               // = 3*300
          status: 'CANCELLED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 3
        },

        // Usuario 2
        {
          id: 6,
          user_id: 2,
          commerce_id: 1,
          address_id: 1,
          created_at: new Date('2024-09-30'),
          total_amount: 1000,              // = 5*200
          status: 'PENDING',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 5
        },
        {
          id: 7,
          user_id: 2,
          commerce_id: 2,
          address_id: 1,
          created_at: new Date('2024-10-01'),
          total_amount: 1100,              // = 3*200 + 1*500
          status: 'DELIVERED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 4
        },
        {
          id: 8,
          user_id: 2,
          commerce_id: 6,
          address_id: 1,
          created_at: new Date('2024-10-02'),
          total_amount: 1200,              // = 4*300
          status: 'DELIVERED',
          delivery_type: 'delivery',
          payment_method: 'mercadopago',
          items_quantity: 4
        },
        {
          id: 9,
          user_id: 2,
          commerce_id: 7,
          address_id: 1,
          created_at: new Date('2024-10-03'),
          total_amount: 1300,              // = 2*400 + 1*500
          status: 'COMPLETED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 3
        },

        // Usuario 3
        {
          id: 10,
          user_id: 3,
          commerce_id: 3,
          address_id: 1,
          created_at: new Date('2024-10-04'),
          total_amount: 1500,              // = 5*300
          status: 'PENDING',
          delivery_type: 'delivery',
          payment_method: 'mercadopago',
          items_quantity: 5
        },
        {
          id: 11,
          user_id: 3,
          commerce_id: 4,
          address_id: 1,
          created_at: new Date('2024-10-05'),
          total_amount: 1600,              // = 4*400
          status: 'CONFIRMED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 4
        },
        {
          id: 12,
          user_id: 3,
          commerce_id: 8,
          address_id: 1,
          created_at: new Date('2024-10-06'),
          total_amount: 1700,              // = 2*400 + 3*300
          status: 'DELIVERED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 5
        },

        // Usuario 4
        {
          id: 13,
          user_id: 4,
          commerce_id: 5,
          address_id: 1,
          created_at: new Date('2024-10-07'),
          total_amount: 3000,              // = 6*500
          status: 'COMPLETED',
          delivery_type: 'delivery',
          payment_method: 'mercadopago',
          items_quantity: 6
        },
        {
          id: 14,
          user_id: 4,
          commerce_id: 6,
          address_id: 1,
          created_at: new Date('2024-10-08'),
          total_amount: 3500,              // = 7*500
          status: 'PENDING',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 7
        },
        {
          id: 15,
          user_id: 4,
          commerce_id: 9,
          address_id: 1,
          created_at: new Date('2024-10-09'),
          total_amount: 4000,              // = 8*500
          status: 'CONFIRMED',
          delivery_type: 'pickup',
          payment_method: 'mercadopago',
          items_quantity: 8
        },
        {
          id: 16,
          user_id: 4,
          commerce_id: 10,
          address_id: 1,
          created_at: new Date('2024-10-10'),
          total_amount: 4500,              // = 5*900
          status: 'DELIVERED',
          delivery_type: 'delivery',
          payment_method: 'mercadopago',
          items_quantity: 5
        },
        {
        id: 100,
        user_id: 1,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2024-11-15'),
        total_amount: 2500,
        items_quantity: 3,
        status: 'CONFIRMED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 101,
        user_id: 2,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2024-12-10'),
        total_amount: 3100,
        items_quantity: 4,
        status: 'DELIVERED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 102,
        user_id: 3,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-01-20'),
        total_amount: 1800,
        items_quantity: 2,
        status: 'COMPLETED',
        delivery_type: 'delivery',
        payment_method: 'cash',
      },
      {
        id: 103,
        user_id: 4,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-02-08'),
        total_amount: 2700,
        items_quantity: 3,
        status: 'CONFIRMED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 104,
        user_id: 2,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-03-18'),
        total_amount: 3200,
        items_quantity: 3,
        status: 'DELIVERED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 105,
        user_id: 1,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-04-09'),
        total_amount: 4100,
        items_quantity: 5,
        status: 'COMPLETED',
        delivery_type: 'delivery',
        payment_method: 'cash',
      },
      {
        id: 106,
        user_id: 3,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-05-23'),
        total_amount: 2800,
        items_quantity: 3,
        status: 'CONFIRMED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 107,
        user_id: 4,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-06-13'),
        total_amount: 3400,
        items_quantity: 4,
        status: 'DELIVERED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 108,
        user_id: 2,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-07-02'),
        total_amount: 3900,
        items_quantity: 5,
        status: 'COMPLETED',
        delivery_type: 'delivery',
        payment_method: 'cash',
      },
      {
        id: 109,
        user_id: 1,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-08-16'),
        total_amount: 2300,
        items_quantity: 3,
        status: 'CONFIRMED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 110,
        user_id: 3,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-09-11'),
        total_amount: 4200,
        items_quantity: 5,
        status: 'DELIVERED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      {
        id: 111,
        user_id: 4,
        commerce_id: 20,
        address_id: 1,
        created_at: new Date('2025-10-05'),
        total_amount: 3600,
        items_quantity: 4,
        status: 'COMPLETED',
        delivery_type: 'delivery',
        payment_method: 'mercadopago',
      },
      // DEMO - últimas 10 “ventanas” mensuales
<<<<<<< HEAD
{
  id: 9101,
  user_id: 3,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 1 MONTH)"),
  total_amount: 4000,
  status: 'CLAIMED',
  delivery_type: 'delivery',
  payment_method: 'mercadopago',
  items_quantity: 2
},
{
  id: 9102,
  user_id: 2,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 2 MONTH)"),
  total_amount: 3200,
  status: 'CLAIMED',
  delivery_type: 'pickup',
  payment_method: 'cash',
  items_quantity: 2
},
{
  id: 9103,
  user_id: 1,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 3 MONTH)"),
  total_amount: 5200,
  status: 'COMPLETED',
  delivery_type: 'delivery',
  payment_method: 'mercadopago',
  items_quantity: 3
},
{
  id: 9104,
  user_id: 4,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 4 MONTH)"),
  total_amount: 1800,
  status: 'COMPLETED',
  delivery_type: 'pickup',
  payment_method: 'cash',
  items_quantity: 1
},
{
  id: 9105,
  user_id: 1,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 5 MONTH)"),
  total_amount: 4100,
  status: 'COMPLETED',
  delivery_type: 'delivery',
  payment_method: 'mercadopago',
  items_quantity: 2
},
{
  id: 9106,
  user_id: 1,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 6 MONTH)"),
  total_amount: 2500,
  status: 'COMPLETED',
  delivery_type: 'pickup',
  payment_method: 'cash',
  items_quantity: 1
},
{
  id: 9107,
  user_id: 3,  
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 7 MONTH)"),
  total_amount: 5900,
  status: 'COMPLETED',
  delivery_type: 'delivery',
  payment_method: 'mercadopago',
  items_quantity: 3
},
{
  id: 9108,
  user_id: 2,
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 8 MONTH)"),
  total_amount: 3400,
  status: 'COMPLETED',
  delivery_type: 'pickup',
  payment_method: 'cash',
  items_quantity: 2
},
{
  id: 9109,
  user_id: Sequelize.literal("FLOOR(1 + (RAND() * 3))"),
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 9 MONTH)"),
  total_amount: 4700,
  status: 'COMPLETED',
  delivery_type: 'delivery',
  payment_method: 'mercadopago',
  items_quantity: 2
},
{
  id: 9110,
  user_id: Sequelize.literal("FLOOR(1 + (RAND() * 3))"),
  commerce_id: 21,
  address_id: 1,
  created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 10 MONTH)"),
  total_amount: 900,
  status: 'COMPLETED',
  delivery_type: 'pickup',
  payment_method: 'cash',
  items_quantity: 1
},
=======
{ id: 9401, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 1 MONTH)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9402, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 1 MONTH), INTERVAL 1 DAY)"), total_amount: 2700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9403, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 1 MONTH), INTERVAL 3 DAY)"), total_amount: 5800, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9404, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 1 MONTH), INTERVAL 5 DAY)"), total_amount: 4600, status: 'PREPARING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
>>>>>>> 7d62832 (Agrego seeders)

{ id: 9405, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 2 MONTH)"), total_amount: 5100, status: 'CONFIRMED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9406, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 1 DAY)"), total_amount: 1700, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9407, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 3 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9408, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 5 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9409, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 7 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9410, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 9 DAY)"), total_amount: 2700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9411, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 2 MONTH), INTERVAL 11 DAY)"), total_amount: 5800, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },

{ id: 9412, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 3 MONTH)"), total_amount: 4600, status: 'PREPARING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9413, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 1 DAY)"), total_amount: 5100, status: 'CONFIRMED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9414, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 3 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9415, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 5 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9416, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 7 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9417, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 9 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9418, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 11 DAY)"), total_amount: 2700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9419, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 13 DAY)"), total_amount: 5800, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9420, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 15 DAY)"), total_amount: 4600, status: 'PREPARING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9421, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 3 MONTH), INTERVAL 17 DAY)"), total_amount: 6900, status: 'CONFIRMED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 4 },

{ id: 9422, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 4 MONTH)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9423, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 1 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9424, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 3 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9425, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 5 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9426, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 7 DAY)"), total_amount: 2700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9427, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 9 DAY)"), total_amount: 5800, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9428, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 11 DAY)"), total_amount: 4600, status: 'PREPARING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9429, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 13 DAY)"), total_amount: 5100, status: 'CONFIRMED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9430, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 15 DAY)"), total_amount: 1700, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9431, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 17 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9432, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 19 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9433, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 21 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9434, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 4 MONTH), INTERVAL 23 DAY)"), total_amount: 2700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },

// ===== MES 5 (hace 5 meses) - 16 órdenes =====
{ id: 9435, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 5 MONTH)"), total_amount: 2300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9436, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 1 DAY)"), total_amount: 1800, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9437, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 2 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9438, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 3 DAY)"), total_amount: 3400, status: 'PREPARING', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9439, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 4 DAY)"), total_amount: 2900, status: 'CONFIRMED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9440, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 5 DAY)"), total_amount: 5200, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9441, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 6 DAY)"), total_amount: 1700, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9442, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 7 DAY)"), total_amount: 4100, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9443, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 8 DAY)"), total_amount: 900, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9444, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 9 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9445, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 10 DAY)"), total_amount: 2600, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9446, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 11 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9447, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 12 DAY)"), total_amount: 2700, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9448, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 13 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9449, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 14 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9450, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 5 MONTH), INTERVAL 15 DAY)"), total_amount: 6300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },

// ===== MES 6 (hace 6 meses) - 19 órdenes =====
{ id: 9451, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 6 MONTH)"), total_amount: 1700, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9452, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 1 DAY)"), total_amount: 5200, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9453, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 2 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9454, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 3 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9455, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 4 DAY)"), total_amount: 4100, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9456, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 5 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9457, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 6 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9458, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 7 DAY)"), total_amount: 900, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9459, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 8 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9460, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 9 DAY)"), total_amount: 2600, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9461, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 10 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9462, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 11 DAY)"), total_amount: 2700, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9463, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 12 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9464, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 13 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9465, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 14 DAY)"), total_amount: 6300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9466, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 15 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9467, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 16 DAY)"), total_amount: 2900, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9468, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 6 MONTH), INTERVAL 17 DAY)"), total_amount: 4100, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },

// ===== MES 7 (hace 7 meses) - 22 órdenes =====
{ id: 9469, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 7 MONTH)"), total_amount: 2300, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9470, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 1 DAY)"), total_amount: 1800, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9471, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 2 DAY)"), total_amount: 5200, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9472, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 3 DAY)"), total_amount: 2600, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 2 },
{ id: 9473, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 4 DAY)"), total_amount: 2900, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9474, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 5 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9475, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 6 DAY)"), total_amount: 4100, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9476, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 7 DAY)"), total_amount: 900, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9477, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 8 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9478, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 9 DAY)"), total_amount: 2600, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9479, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 10 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9480, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 11 DAY)"), total_amount: 2700, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9481, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 12 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9482, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 13 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9483, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 14 DAY)"), total_amount: 6300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9484, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 15 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9485, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 16 DAY)"), total_amount: 2900, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9486, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 17 DAY)"), total_amount: 4100, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9487, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 7 MONTH), INTERVAL 18 DAY)"), total_amount: 1700, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },

// ===== MES 8 (hace 8 meses) - 25 órdenes =====
{ id: 9488, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(NOW(), INTERVAL 8 MONTH)"), total_amount: 2300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9489, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 1 DAY)"), total_amount: 1800, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9490, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 2 DAY)"), total_amount: 5200, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9491, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 3 DAY)"), total_amount: 2600, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 2 },
{ id: 9492, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 4 DAY)"), total_amount: 2900, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9493, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 5 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9494, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 6 DAY)"), total_amount: 4100, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9495, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 7 DAY)"), total_amount: 900, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9496, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 8 DAY)"), total_amount: 5800, status: 'PENDING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9497, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 9 DAY)"), total_amount: 2600, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9498, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 10 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9499, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 11 DAY)"), total_amount: 2700, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9500, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 12 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9501, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 13 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9502, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 14 DAY)"), total_amount: 6300, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9503, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 15 DAY)"), total_amount: 3400, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9504, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 16 DAY)"), total_amount: 2900, status: 'PREPARING', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 1 },
{ id: 9505, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 17 DAY)"), total_amount: 4100, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 3 },
{ id: 9506, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 18 DAY)"), total_amount: 1700, status: 'ON_THE_WAY', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 1 },
{ id: 9507, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 19 DAY)"), total_amount: 5200, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9508, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 20 DAY)"), total_amount: 1800, status: 'CANCELLED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },
{ id: 9509, user_id: 3, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 21 DAY)"), total_amount: 4600, status: 'COMPLETED', delivery_type: 'delivery', payment_method: 'mercadopago', items_quantity: 2 },
{ id: 9510, user_id: 4, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 22 DAY)"), total_amount: 2700, status: 'CONFIRMED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 3 },
{ id: 9511, user_id: 1, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 23 DAY)"), total_amount: 2300, status: 'ON_THE_WAY', delivery_type: 'delivery', payment_method: 'cash', items_quantity: 1 },
{ id: 9512, user_id: 2, commerce_id: 21, address_id: 1, created_at: Sequelize.literal("DATE_SUB(DATE_SUB(NOW(), INTERVAL 8 MONTH), INTERVAL 24 DAY)"), total_amount: 1800, status: 'COMPLETED', delivery_type: 'pickup', payment_method: 'cash', items_quantity: 2 },

      ], {});
    } catch (error) {
      console.error('Error executing seeder (order):', error);
      throw error;
    }
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('order', null, {});
  }
};
