name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Connect to EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/Comidin-Backend
          git pull origin main

          echo "Generating .env from SSM parameters under /comidin-back/"
          aws ssm get-parameters-by-path \
            --path "/comidin-back/" \
            --with-decryption \
            --recursive \
            --region us-east-1 \
            --query "Parameters[*].[Name,Value]" \
            --output text | while read name value; do
              key=$(basename "$name")
              echo "$key=$value" >> .env
          done

          echo "Cleanup Docker system..."
          sudo docker system prune -a --volumes -f

          echo "Stopping and removing old containers..."
          sudo docker compose down

          echo "Building and starting containers with Docker Compose..."
          sudo docker compose up -d --build
